### ISSUE TITLE
typos in REDCap and Sequencing data RDMbites tiles

### ISSUE THREAD

**Issue by egdelva** [ELIXIR-UK-DaSH/FAIR-DaSH#14]
https://fellowship.elixiruknode.org/rdmbites

in both **specialised** is spelt incorrectly

**Comment by kkamieniecka** [comment]
Hi @egdelva thank you for your feedback
Issue is open in the wrong repository moving it to; https://github.com/ELIXIR-UK-DaSH/fellowship
