### ISSUE TITLE
markup not working in solutions

### ISSUE THREAD

**Issue by robertmand** [ELIXIR-UK-DaSH/FAIR-DaSH#21]
For example: episode one: The stars can be seen

Not so obviously shared terms are: **vocabularies** (I1, I2), **access** (A1, A1.1, A1.2, R1.1)

**Comment by egdelva** [comment]
Was going to write an issue but see this is here already, so just adding a screenshot as I've seen this in solutions throughout.

<img width="232" alt="image" src="https://github.com/ELIXIR-UK-DaSH/FAIR-DaSH/assets/126821518/68fe1658-fb32-41f3-81ef-593093e0cb97">
